Quasars/orange-spectroscopy

- orangecontrib/infrared/widgets/owpreproc.py
Added Savitzky-Golay Filtering for smoothing and differentiation of spectra to the preprocessing function.
> Add Savitzky-Golay Filtering as a preprocessor

- orangecontrib/infrared/widgets/owpreproc.py
This allows spectra to be normalized by some attribute, for example pellet weight percent.
Currently it only shows meta attributes as the normal attributes are all wavenumbers and overwhelm the dialog.
Closes #13
> Normalize: Implement normalize by attribute

- orangecontrib/infrared/widgets/owpreproc.py
Integration preprocessor, allows:
- Multiple, dynamic spectral windows
- Multiple integration methods: y=0, baseline-subtracted, peak height at max, baseline or specified freq
- Window selection with gui markers
Closes #17
> Integration preprocessor

- orangecontrib/infrared/widgets/owpreproc.py
Small fix for initialization of integration preprocessor
> Integrate: handle empty limits lists and change default

- orangecontrib/infrared/data.py
- orangecontrib/infrared/pymca5/DataObject.py
- orangecontrib/infrared/pymca5/OmnicMap.py
Can read some files. Works properly with 150416-01 degman 10x10µm² 5x10 spc.map but not with dlg_cls_1.map (PyMca did not extract metainfo for that file).
> Omnic reader with PyMca

- orangecontrib/infrared/widgets/owpreproc.py
PCA denoising requires Orange from the master branch or Orange snapshot >= 20160910
> preprocess: PCA denoising

- orangecontrib/infrared/widgets/owpreproc.py
These commits fix a number of small crashes and weird behaviour in the integrate preprocessor.
> Small fixes to integrate preprocessor

- orangecontrib/infrared/irfft.py
- orangecontrib/infrared/widgets/owfft.py
- irfft.fft_single_sweep() now outputs phase
- owfft.fft_single() now expects and outputs phase
> fft: output phase spectrum as well as amplitude (Fixes #39)

- orangecontrib/infrared/preprocess.py
- orangecontrib/infrared/tests/test_absorbance.py
- orangecontrib/infrared/widgets/owpreproc.py
This version only exposes conversion from AB -> TR and TR -> AB but the goal is to use for calculation from single-channel data as well.
I thought I would push this first to make sure I'm using the new preprocessor framework properly. And tests!
> Absorbance / Transmittance preprocessors

- orangecontrib/infrared/widgets/owcurves.py
This is code by @borondics from PR #54 with added state saving and minor changes. What do you think?
> Resample curves

- orangecontrib/infrared/data.py
OK, I am trying to test both the file handling and moved up the x_locs on the top in case that gives an exception.
> Improved exception handling for the specific HERMES HDF5 reader

- orangecontrib/infrared/widgets/owpreprocess.py
Stylesheets do not work well on Macs
> owproprecess: use toggle button instead of stylesheets for "Final preview"

- orangecontrib/infrared/tests/test_owspectra.py
- orangecontrib/infrared/tests/test_utils.py
- orangecontrib/infrared/widgets/owhyper.py
- orangecontrib/infrared/widgets/owintegrate.py
- orangecontrib/infrared/widgets/owspectra.py
- orangecontrib/infrared/widgets/utils.py
Used in planned multiple selections
> spectra: selections now use selection groups

- orangecontrib/infrared/tests/test_owspectra.py
- orangecontrib/infrared/tests/test_utils.py
- orangecontrib/infrared/widgets/owhyper.py
- orangecontrib/infrared/widgets/owintegrate.py
- orangecontrib/infrared/widgets/owspectra.py
- orangecontrib/infrared/widgets/utils.py
Preparation for multiple selections.
> spectra: selections now use selection group

- orangecontrib/infrared/tests/test_owhyper.py
- orangecontrib/infrared/tests/test_owspectra.py
- orangecontrib/infrared/widgets/owhyper.py
- orangecontrib/infrared/widgets/owspectra.py
- orangecontrib/infrared/widgets/utils.py
Unified selection saving between Hyper and Spectra
> Hyper uses selection_group structure

- orangecontrib/infrared/preprocess.py
- orangecontrib/infrared/tests/test_interpolate.py
- orangecontrib/infrared/tests/test_owinterpolate.py
- orangecontrib/infrared/widgets/owinterpolate.py
Predictions in the fourth workflow on the image now work.
> Interpolate creates the same features in "Reference data" mode

- orangecontrib/infrared/agilent.py
- orangecontrib/infrared/data.py
Does what it says on the tin.
Credit to Alex Henderson for the MATLAB code this is based on.
https://bitbucket.org/AlexHenderson/agilent-file-formats
> Add file readers for Agilent (Resolutions Pro) image and mosaic files

- README.pypi
- setup.py
Any objections? @stuart-cls, @GioB81
> Rename widget category: Infrared -> Spectroscopy

- orangecontrib/infrared/tests/test_owhyper.py
- orangecontrib/infrared/tests/test_owspectra.py
- orangecontrib/infrared/tests/util.py
- orangecontrib/infrared/widgets/owhyper.py
- orangecontrib/infrared/widgets/owspectra.py
Similar selection of multiple groups as in Scatter plot.
Difference between selected groups is not yet shown in Spectra because I do not have a good idea how should it look.
> Hyper and Spectra: multiple group selection

- orangecontrib/infrared/preprocess.py
- orangecontrib/infrared/tests/test_owpreprocess.py
- orangecontrib/infrared/tests/test_preprocess.py
- orangecontrib/infrared/widgets/owpreprocess.py
Added a linear baseline to the Preprocessing widget
> Linearbaseline

- orangecontrib/infrared/preprocess.py
- orangecontrib/infrared/tests/test_preprocess.py
- orangecontrib/infrared/widgets/owpreprocess.py
Cleaned up #132 
@borondics , can you check if it still works as it should?
>  Add spectrum shift preprocessor

- orangecontrib/spectroscopy/tests/test_owinterpolate.py
- orangecontrib/spectroscopy/tests/test_owreshape.py
- orangecontrib/spectroscopy/widgets/gui.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
Trying to make new preprocessors shorter to write by reusing Orange's settings and gui functions
> owreprocess refactor

- .travis.yml
- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/tests/test_integrate.py
- orangecontrib/spectroscopy/tests/test_owmultifile.py
- orangecontrib/spectroscopy/tests/test_owreshape.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owspectra.py
- setup.py
Remove some unneeded code and fix deprecation warnings.
> Require Orange 3.7.0

- orangecontrib/spectroscopy/data.py
Removed explicit loops from _spectra_from_image.
> Speedup image reading

- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owspectra.py
> [FIX] graph saving in widgets with multiple graphs

- orangecontrib/spectroscopy/widgets/owhyper.py
> [FIX] Hyperspectra: moving integral region should not change outputs

- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owspectra.py
Fixes Sentry ORANGE-SPECTROSCOPY-10
> Fix a crash with only infs and nans

- CONTRIBUTING.md
- README.md
I used the puppet CONTRIBUTING as a template.
> A start on CONTRIBUTING documentation, as raised in #188

- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
The settings entered are now always valid and are executed as they are.
The preview is shown directly after editing any of the settings.
> owpreprocess: reworked Savitzky-Golay editor

- orangecontrib/spectroscopy/widgets/owpreprocess.py
> Changed initialization of the limit lines in Preprocess Spectra/Cut

- orangecontrib/spectroscopy/widgets/gui.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
Trying to solve a problem @borondics mentioned in #202.
> Preprocess Spectra/Cut: round initial values

- orangecontrib/spectroscopy/tests/test_owaverage.py
- orangecontrib/spectroscopy/widgets/owaverage.py
Created widget to average spectra
> Added averaging widget

- orangecontrib/spectroscopy/preprocess/emsc.py
- orangecontrib/spectroscopy/tests/test_conversion.py
- orangecontrib/spectroscopy/tests/test_emsc.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
Added functionality for bad spectra input in EMSC.
> [ENH] EMSC supports bad spectra input

- orangecontrib/spectroscopy/widgets/owspectra.py
Removes a deprecation warning.
> Import HelpEventDelegate from the new location.

- orangecontrib/spectroscopy/tests/test_owaverage.py
- orangecontrib/spectroscopy/widgets/owaverage.py
- remove unused imports
- small naming corrections
Just a few leftovers from #219 before starting on averaging by group, #231
> OWAverage: small cleanups

- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owspectra.py
The goal of this is to be able to see which curve in preprocess previews. Requested by @oroue.
> [ENH] CurvePlot: an option to color individual curves

- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owspectra.py
> CurvePlot: fix average with unknown feature value

- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owspectra.py
> Spectra: correct sampling info in average view

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
Fix the reason #246 is still failing
>  Fix PCADenoising to work with refactored Orange projection 

- orangecontrib/spectroscopy/agilent.py
- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_readers.py
Add support for reading agilent interferogram data files, including metadata required to calculate FFT properly (See #261)
Closes #243
> [ENH] Agilent read interferogram data (seq and drd)

- orangecontrib/spectroscopy/preprocess/emsc.py
- orangecontrib/spectroscopy/preprocess/integrate.py
- orangecontrib/spectroscopy/tests/test_integrate.py
- orangecontrib/spectroscopy/tests/test_owreshape.py
- orangecontrib/spectroscopy/widgets/owreshape.py
get_next_name will be removed in Orange 3.20 (biolab/orange3#3486)
> Replace get_next_name by get_unique_names

- orangecontrib/spectroscopy/widgets/owmultifile.py
It does not make sense to populate this widget when a user adds it onto the canvas. @oroue
> Multifile: make settings schema only

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_owfft.py
- orangecontrib/spectroscopy/tests/test_readers.py
- orangecontrib/spectroscopy/widgets/owfft.py
The meta data (X and Y image positions) were lost after FFT.
> [FIX] FFT widget: keep metas

- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
Also some minor maintenance and comments.
> [FIX] Preprocess widget: always output preprocessor (also on no input data)

- orangecontrib/spectroscopy/widgets/owstackalign.py
Added a graph showing the shift curves for the Stack Alignment widget.
> [ENH] Feedback on Stack Alignment

- orangecontrib/spectroscopy/tests/test_owalignstack.py
- orangecontrib/spectroscopy/widgets/gui.py
- orangecontrib/spectroscopy/widgets/owstackalign.py
Added reference frame change option
Added tests
> [ENH] Enable changing the reference frame in Stack Align

- README.md
- doc/conf.py
- doc/index.rst
Reference Quasar as the preferred installation.
> Update README and the first documentation page

- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
What is not tested does not exist...
> Fix preprocessor warnings for pre-3.20 Orange

- orangecontrib/spectroscopy/tests/spectral_preprocess.py
- orangecontrib/spectroscopy/tests/test_owintegrate.py
- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/widgets/owintegrate.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
I created that bug when I also started processing reference in #287. @stuart-cls noticed that something was off in #301.
It was another case of "what is not tested does not exist", so I added some tests.
> [FIX] OWIntegrate: fix non-meta output

- orangecontrib/spectroscopy/data.py
A very case specific reader. Adding it as a separate PR (splitting #206 into smaller pieces).
I am not following the Beyonce principle (https://www.youtube.com/watch?start=1076&v=TrC6ROeV4GI): I don't have any small files to put into the repository. @oroue should provide a (very small) test file.
But merging this now certainly makes rebasing / editing #206 easier.
> Rock XAS reader

- orangecontrib/spectroscopy/widgets/owfft.py
> [FIX] Interferogram to Spectrum: fix zero-filling factor

- orangecontrib/spectroscopy/tests/test_owmultifile.py
- orangecontrib/spectroscopy/widgets/owmultifile.py
> Multi file reader: remove subclassing OWFile

- orangecontrib/spectroscopy/tests/test_owintegrate.py
- orangecontrib/spectroscopy/widgets/owintegrate.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
The integrate widget now complains when some limit is out of data range. Closes #30.
> [ENH] Integrate range warnings

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/datasets/nea_test_v2.txt
- orangecontrib/spectroscopy/tests/test_readers.py
Neaspec new files did not work.
> [ENH] New reader for neaspec files

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/utils/__init__.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owspectralseries.py
- orangecontrib/spectroscopy/widgets/owstackalign.py
I found the hypercube-building code in owalignstack very useful, and I'd been using this refactored version in some scripts for a while. Since I need a hypercube for the binning widget, I thought I'd break it out for all to use.
Thoughts?
> Refactor hypercube

- orangecontrib/spectroscopy/widgets/icons/bin.svg
Added icon for the new binning widget.
> Icon for binning

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/tests/test_editor_baseline.py
- orangecontrib/spectroscopy/tests/test_editor_gaussian.py
- orangecontrib/spectroscopy/tests/test_editor_normalize.py
- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
> [FIX] Gaussian smoothing sd~0 is intepreted as no smoothing

- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owspectralseries.py
> [ENH] Color legend for images.

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/utils/__init__.py
- orangecontrib/spectroscopy/widgets/owhyper.py
Fixes #349
I also saw this reported quite often as a crash report, but could not figure out what was causing it.
> [FIX] HyperSpectra: do not crash on undefined positions

- orangecontrib/spectroscopy/preprocess/__init__.py
With the previous settings results were not reproducible.
> [FIX] PCA denoising reproducibility

- doc/widgets/spectra.rst
- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owspectra.py
- orangecontrib/spectroscopy/widgets/owspectralseries.py
Also allow selection with mouse drags.
> [ENH] Spectra, Hyper: selection also with mouse drag

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/tests/test_conversion.py
- orangecontrib/spectroscopy/tests/test_interpolate.py
Fix tests to work with biolab/orange3#3925
> Fix tests for removal of Variable.make

- doc/widgets.json
It will be shown at https://orange.biolab.si/widget-catalog/
> Add documentation index for the webpage

- orangecontrib/spectroscopy/preprocess/me_emsc.py
- orangecontrib/spectroscopy/tests/test_editor_me_emsc.py
- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
- orangecontrib/spectroscopy/widgets/preprocessors/emsc.py
- orangecontrib/spectroscopy/widgets/preprocessors/me_emsc.py
- orangecontrib/spectroscopy/widgets/preprocessors/normalize.py
- orangecontrib/spectroscopy/widgets/preprocessors/utils.py
Simplest possible addition of ME-EMSC preprocessor. It only shows one parameter to the user.
> [ENH] ME-EMSC in Preprocess Spectra widget

- orangecontrib/spectroscopy/widgets/owspectra.py
> Spectra: fix individual color shortcut

- doc/widgets/spectra.md
> Spectra doc: on changing colors

- .travis.yml
- conda/meta.yaml
- orangecontrib/spectroscopy/tests/spectral_preprocess.py
- orangecontrib/spectroscopy/tests/test_editor_baseline.py
- orangecontrib/spectroscopy/tests/test_editor_emsc.py
- orangecontrib/spectroscopy/tests/test_editor_gaussian.py
- orangecontrib/spectroscopy/tests/test_editor_me_emsc.py
- orangecontrib/spectroscopy/tests/test_editor_normalize.py
- orangecontrib/spectroscopy/tests/test_owintegrate.py
- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/widgets/owintegrate.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
- orangecontrib/spectroscopy/widgets/preprocessors/baseline.py
- orangecontrib/spectroscopy/widgets/preprocessors/utils.py
- setup.py
> [ENH] More responsive Preprocess and Integrate widgets; progress bars

- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/utils/__init__.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owspectra.py
- compute averages in a separate thread
> [ENH] Responsive Spectra widget

- orangecontrib/spectroscopy/tests/test_utils.py
- orangecontrib/spectroscopy/utils/__init__.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
- orangecontrib/spectroscopy/widgets/owspectra.py
Disconnecting data now stops processing, changed settings are (almost) immediately applied.
Merge after #399
> Hyperspectra: users can interrupt image computation

- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owspectra.py
> owspectra: fix color settings test for Orange master

- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owspectra.py
in owspectra: subclass PlotCurveItem to filter non-finite values from Qt
fixes #408
> [FIX] Filter non-finite values from spectra plot

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owspectra.py
Needed for compatibility with Orange 3.26.0.
Fixes #411 and problem @borondics, who is working with Orange master, had yesterday.
> CurvePlot: feature_color is always a Variable

- orangecontrib/spectroscopy/models/modelling/pls.py
- orangecontrib/spectroscopy/models/pls.py
- orangecontrib/spectroscopy/tests/test_owpls.py
- orangecontrib/spectroscopy/widgets/owpls.py
Replaces #417, only works for 1D Y variables.
> [ENH] Partial least squares regressor

- orangecontrib/spectroscopy/widgets/icons/PLS.svg
- orangecontrib/spectroscopy/widgets/owpls.py
Only cosmetics:
- added a PLS icon based on the PCA widget icon
- changed the reference in the owpls.py file
> PLS widget icon

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/tests/test_editor_normalize.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/widgets/preprocessors/normalize.py
Part of #432
Doesn't implement ranges yet.
Clone of #435
> [ENH] Normalize: add Min-max normalization

- orangecontrib/spectroscopy/irfft.py
- orangecontrib/spectroscopy/tests/test_owfft.py
- orangecontrib/spectroscopy/widgets/owfft.py
Hi, @stuart-cls,
This is the [part 1](https://github.com/Quasars/orange-spectroscopy/issues/416#issuecomment-626056535), with:
- Unit Test;
- Check_metadata();
- Complex FFT as an inherited class.
[Real FFT](https://user-images.githubusercontent.com/50185701/81973933-3ebb1780-95fb-11ea-9ade-627c09092030.png), [Complex FFT](https://user-images.githubusercontent.com/50185701/81973963-45e22580-95fb-11ea-834a-a5e205a1fd97.png)
Discussion here #416 and #423
> [ENH] s-SNOM FFT Processing: Class complex fft part1

- orangecontrib/spectroscopy/irfft.py
- orangecontrib/spectroscopy/tests/test_owfft.py
- orangecontrib/spectroscopy/widgets/owfft.py
I have no idea why does Travis ignore @levandoskije's PRs (it also ignored the previous ones).
> [NOMERGE] Test PR440

- orangecontrib/spectroscopy/tests/test_conversion.py
In Orange, LogisticRegression was changed to do softmax for multiple classes.
> Fix tests for Orange master

- orangecontrib/spectroscopy/models/pls.py
- orangecontrib/spectroscopy/tests/test_owpls.py
Replaces #426
This leaves the widget as is and only modifies the actual modelling classes.
> [FIX] PLS: use at most as many components as features

- doc/conf.py
`app.add_stylesheet` is deprecated
changed to 
`app.add_css_file`
> Fix Sphinx setting

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/widgets/preprocessors/normalize.py
I created a new standardization pre-process by reference for the s-SNOM phase, called:
`Normalize phase by reference subtraction`
I tried to modify the code a little so that I could make the most of the existing features.
Hi @stuart-cls, this PR makes part of issue  #416.
> [ENH] Normalize Phase of complex data

- orangecontrib/spectroscopy/widgets/owfft.py
The tests were otherwise failing on my computer.
> owfft: reorganize interface into two columns

- .travis.yml
- .travis/install_orange.sh
- orangecontrib/spectroscopy/tests/test_conversion.py
- orangecontrib/spectroscopy/tests/test_owaverage.py
- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- old versions need specified orange-widget-base and orange-canvas-core
- fix tests so that master works
> Fix travis tests to to work with updated Orange

- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owmultifile.py
- orangecontrib/spectroscopy/widgets/owspectra.py
"File" search not showing the Multifile widget. :) Thanks to Christophe.
> New keywords so that users can find widgets more easily

- orangecontrib/spectroscopy/irfft.py
- orangecontrib/spectroscopy/tests/test_owfft.py
- orangecontrib/spectroscopy/widgets/owfft.py
Hi @stuart-cls !
I did some testing and it is possible to use the standard apodization and centering available.
So, I modified the code and now we have only one function to do this pre-processing.
This PR is a continuation of  PR #440  , issue #416  and I fixed some minor errors from the old one.
- Blocked spacing editing;
- Blocked sweep editing
- Apodization;
- Centralization;
- Zero filling;
- Update tests;
> [ENH] s-SNOM FFT Processing: Class complex fft part2

- orangecontrib/spectroscopy/irfft.py
- orangecontrib/spectroscopy/tests/test_owfft.py
- orangecontrib/spectroscopy/widgets/owfft.py
Fake PR to trigger the CI tests
> [NOMERGE] Fft apodization

- orangecontrib/spectroscopy/data.py
> Fix compatibility with h5py 3.0

- orangecontrib/spectroscopy/pymca5/OmnicMap.py
@clsandt found an Omnic Map which Quasar reads incorrectly.
Omnic files are read with PyMCA. Here I updated the reader to the latest PyMCA version, to see if that fixed the problem. This did not help with that file though, but still it is better to be current (they fixed some bugs).
> OmnicMap reader: update to master of PyMCA

- doc/widgets/als.md
- doc/widgets/preprocess-spectra.md
- orangecontrib/spectroscopy/preprocess/als.py
- orangecontrib/spectroscopy/preprocess/als/__init__.py
- orangecontrib/spectroscopy/preprocess/als/baseline.py
- orangecontrib/spectroscopy/tests/test_als.py
- orangecontrib/spectroscopy/tests/test_editor_als.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
- orangecontrib/spectroscopy/widgets/preprocessors/als.py
I've added the ALS Smoothing  modules I mentioned in the issues. I believe I covered all the tests needed but let me know if I'm missing anything, or if there is anything else I need to change. If needed I can add in the documentation that was  in their [collection](https://irfpy.irf.se/projects/ica/_modules/irfpy/ica/baseline.html) but I wasn't sure if that was needed.
> [ENH] Asymmetric Least Squares Smoothing

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
New preprocessor to subtract spectra from one another. Next feature will be automatic optimization for multiple spectra. Use case e.g. water subtraction.
> Spectrum Subtraction Preprocessor

- orangecontrib/spectroscopy/models/pls.py
- orangecontrib/spectroscopy/tests/test_owpls.py
The new implementation crashed on our test inputs (now they are a bit stricter). See scikit-learn/scikit-learn#17095
> [MNT] Adapt PLS for scikit-learn 0.24.0

- orangecontrib/spectroscopy/data.py
> Allow csv extension in Spectra ASCII reader

- orangecontrib/spectroscopy/preprocess/als/baseline.py
- orangecontrib/spectroscopy/preprocess/emsc.py
- orangecontrib/spectroscopy/preprocess/me_emsc.py
- orangecontrib/spectroscopy/tests/test_conversion.py
- orangecontrib/spectroscopy/tests/test_interpolate.py
- orangecontrib/spectroscopy/utils/__init__.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owreshape.py
- orangecontrib/spectroscopy/widgets/owspectra.py
- orangecontrib/spectroscopy/widgets/preprocessors/utils.py
Handle some deprecations (warnings) or compatibility with non-supported Orange versions
> Deprecations

- orangecontrib/spectroscopy/tests/test_owmultifile.py
> owmultiple tests: remove support for old Orange

- orangecontrib/spectroscopy/tests/test_owreshape.py
- orangecontrib/spectroscopy/widgets/owreshape.py
> [ENH] Reshape Map: can invert individual axes

- orangecontrib/spectroscopy/__init__.py
- orangecontrib/spectroscopy/io/agilent.py
- orangecontrib/spectroscopy/io/ascii.py
- orangecontrib/spectroscopy/io/util.py
- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/preprocess/transform.py
- orangecontrib/spectroscopy/preprocess/utils.py
- orangecontrib/spectroscopy/tests/test_conversion.py
- orangecontrib/spectroscopy/tests/test_interpolate.py
- orangecontrib/spectroscopy/tests/test_irfft.py
- orangecontrib/spectroscopy/tests/test_owalignstack.py
- orangecontrib/spectroscopy/tests/test_owaverage.py
- orangecontrib/spectroscopy/tests/test_owbin.py
- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/tests/test_owpeakfit.py
- orangecontrib/spectroscopy/tests/test_owpls.py
- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/tests/test_owspectralseries.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/widgets/owaverage.py
- orangecontrib/spectroscopy/widgets/owfft.py
- orangecontrib/spectroscopy/widgets/owmultifile.py
- orangecontrib/spectroscopy/widgets/owpeakfit.py
- orangecontrib/spectroscopy/widgets/owreshape.py
- orangecontrib/spectroscopy/widgets/owsnr.py
> Adapt for Orange's table-lock

- orangecontrib/spectroscopy/widgets/owpls.py
- pyproject.toml
Also fix a owpls test that was failing on newest
> [FIX] Installation with newer pip/setuptools

- conda/meta.yaml
- setup.py
- tox.ini
See issue https://github.com/pyqtgraph/pyqtgraph/issues/2237, which will be fixed in next pyqtgraph release.
> Ignore pyqtgraph 0.12.4 due to changed updateScaleBox semantics

- orangecontrib/spectroscopy/utils/agilent.py
A series of case-sensitivity bugs like #620. This time it affects data loading. Some were due to non-standard naming from reprocessed datasets, and some were triggered by a race condition in the directory listing code.
Again, I added tests to my [parallel repo](https://github.com/stuart-cls/python-agilent-file-formats) so I only propose the changes to the module here. I may release the module in the future but for now I will not.
> [FIX] Agilent loading edge-cases on case-sensitive systems

- orangecontrib/spectroscopy/preprocess/integrate.py
- orangecontrib/spectroscopy/preprocess/utils.py
- orangecontrib/spectroscopy/tests/test_integrate.py
- orangecontrib/spectroscopy/widgets/owintegrate.py
- orangecontrib/spectroscopy/widgets/preprocessors/integrate.py
- tox.ini
As suggested by @clsandt, @borondics and I worked a bit on this one today.
> [ENH] Integrate with a separate baseline

- orangecontrib/spectroscopy/widgets/owintegrate.py
While working on #634 I found a call to commit that got missed in #622
I wasn't sure which call ("now" or "deferred") was appropriate, I chose "now"
> [FIX] Integrate: Fix call to new deferred commit

- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owspectra.py
An option to show spectra in a stacked form. For now we do not have parameters how much to move the spectra. but that can be added later.
> [ENH] Spectra: waterfall plot

- .github/workflows/test.yml
The old machine is not available anymore.
> update macos runner

- .github/workflows/test.yml
- conda/meta.yaml
- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/tests/test_readers.py
- orangecontrib/spectroscopy/widgets/line_geometry.py
- orangecontrib/spectroscopy/widgets/owspectra.py
- setup.py
- tox.ini
All functionality should now also work for Dask tables, albeit perhaps slower. 
In the future, individual curve display should work in the same way as average curves, which means it should be implemented in a thread.
> [ENH] Spectra: dask table support

- orangecontrib/spectroscopy/models/pls.py
- orangecontrib/spectroscopy/widgets/owpls.py
Scikit-learn changed how PLS behaves, thus fixes are needed
> Fix PLS for scikit-learn 1.3

- .github/workflows/test.yml
Need a baseline for all the current test failures
> [TEST] Enable workflow dispatch for main tests

- setup.py
> [FIX] Bump lmfit version to 1.3.2

- orangecontrib/spectroscopy/io/__init__.py
- orangecontrib/spectroscopy/io/cls.py
- orangecontrib/spectroscopy/io/meta.py
Loads 4D stacks from the SGM beamline at the CLS. Primary energy axis (features) is the XRF energy (MCA).
Notes:
* No test file, will try to get one
* These are Nexus-compatible files, so future work is to make a more generic nexus reader and subclass that 
* Missing piece is tool to rotate primary energy axis after ROI integration, I'll do that as a separate PR
> [ENH] File reader for 4D mapping stacks from the SGM beamline at CLS

- orangecontrib/spectroscopy/widgets/preprocessors/misc.py
I made the PCA denoising preprocessor layout the same as the new MNF denoising. I think it is easier for the users to understand what is happening like this.
> PCA denoising layout change

- orangecontrib/spectroscopy/widgets/preprocessors/misc.py
This fixes a bug where changing the number of components did not immediately update the preview (we had to wait until focus-out).
@borondics, please check if this works and then also update your preprocessor accordingly. :) Rebase first after this branch is merged.
> PCA denoising: extent BaseEditorOrange

- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
A more general preprocessor widget that allows other kinds of previews.
This is support work for Quasars/orange-snom/pull/7
> [MNT] Support for Preprocess images from the SNOM addon

- orangecontrib/spectroscopy/widgets/line_geometry.py
- orangecontrib/spectroscopy/widgets/owhyper.py
> [ENH] HyperSpectra: show value traces of selected lines

- orangecontrib/spectroscopy/io/neaspec.py
This will put all readers in the menu together so easier to use.
> changed reader name

- .readthedocs.yaml
> [MAINT] readthedocs: Install extra_requirements "doc"

- orangecontrib/spectroscopy/widgets/owfft.py
This might be a bad fix, maybe AnyQt should handle this, but it has implications for orange3 as well?
> FFT widget: use WidgetPreview
