Quasars/orange-spectroscopy

- orangecontrib/infrared/widgets/owpreproc.py
This calculates a rubberband baseline using the convex hull approach.
Notes:
- I imported getx() from owcurves to avoid duplicating this (very) important function, but I think it should be sanity-checked and put into data.py or similar
- I included an option to only show the calculated baseline without subtracting. Obviously not useful in repetitive calculations but I'm nervous about including baseline subtraction without a way for the user to check that a reasonable baseline was built.
- The scipy interp1d function can do other kinds of interpolation than linear, is this a useful option to expose in the GUI?
- Line 232 does a `copy.copy(data)`, which I based off the Gaussian preproc. Do we need to do this copy (doubles memory usage)? And if we do, why use `copy.copy(data)` instead of …
> [owpreproc] Rubberband baseline subtraction

- orangecontrib/infrared/widgets/owpreproc.py
Two small fixes for salgol_filter preproc.
[owpreproc] Window spinbox should have value=self.window
[owpreproc] Change savgol_filter to use data.copy() as well
> Fix savgol preproc

- orangecontrib/infrared/widgets/owpreproc.py
Here is a (spectral) normalization preprocessor. It implements:
- Simple min-max scaling
- Vector normalization
- Offset correction
with the option of limiting the normalization criteria to a specific spectral range.
Another thing we need to do with this widget is normalize to a meta attribute, for example scaling by a weight percent to correct for KBr pellet thickness. I was unable to figure out a good way of filling a combo box with the meta/class attributes of the data, since the BaseEditor isn't aware of what data is connected to it as far as I can tell. Help?
> [owpreproc] Normalization preprocessor

- orangecontrib/infrared/widgets/owpreproc.py
This PR uses the new gui markers to set the normalization limits (when desired).
Also includes some work to bring NormalizeEditor up to the level of CutEditor and some dataset sets to avoid crashing when passed an empty dataset (for example, from Cut set to 0.0-1.0)
> [owpreproc] Set normalization limits using gui markers

- orangecontrib/infrared/widgets/owpreproc.py
It is possible that the dataset may contain rows with NaNs in the attributes, which causes Qhull to error out. This adds a try-except block to handle that error. 
Can be easily triggered by normalizing by an attribute that is NaN
> Fix preproc rubberband

- orangecontrib/infrared/widgets/owpreproc.py
Test dataset on fresh Windows install triggered this error:
```
TypeError: ufunc 'true_divide' output (typecode 'O') could not be coerced to provided
output parameter (typecode 'd') according to the casting rule ''same_kind''
```
> [owpreproc] Normalize: Ensure factors array is floats for type safe true_divide 

- orangecontrib/infrared/data.py
- orangecontrib/infrared/widgets/owpreproc.py
Identically named variables won't test as equal unless .make() is used[1]
[1] http://docs.orange.biolab.si/3/data-mining-library/reference/data.variable.html#constructors
> Use ContinuousVariable.make() constructor consistently

- orangecontrib/infrared/widgets/owpreproc.py
Our users are having difficulty matching attributes between training and test data with the coerced value naming I was using before. This approach will also be more consistent between datasets and allows the user to apply a constant window regardless of data spacing.
> Integrate: Match produced attribute name to user-defined window

- orangecontrib/infrared/data.py
- setup.py
This PR will add the ability to load OPUS binary files. It depends on the opusFC module:
Issues to discuss before merging:
1. I didn't rebase on the latest master as I noticed that #33 requires a version of Orange later than what our users can install (only 3.3.7 is available so far)
2. I added opusFC to `install_requires` but I'm not sure about this: on the one hand, it means users installing orange-infrared automatically get OPUS support. But the downside is that users with problems with installing opusFC will be unable to install orange-infrared at all. I'm not sure there is a great solution to this.
3. I haven't quite got MacOS .whls of opusFC up yet, so sorry Feri :)
I look forward to your comments and suggestions.
> Opus reader

- README.md
See:
[1] https://github.com/pypa/setuptools/issues/78
[2] https://github.com/biolab/orange3-example-addon
Does this bug cause a problem with the installation from the Add-ons menu in Orange?
> Change README.md to reflect that setuptools doesn't support wheels

- orangecontrib/infrared/widgets/owfft.py
Small fix to interferogram-sniffing code to make less assumptions about the initial interferogram size.
> irfft: Calculate zpd center variation as a percentage of interferogram size

- orangecontrib/infrared/data.py
- setup.py
This PR adds support for OpusFC 1.1.0 including:
- multiregion 3D map files
- time-resolved 3D files
Other changes:
- Direct data structure matching using return Object type (instead of guessing)
- Simplification of parameter reading code, including a fix to a previously unused code path.
@markotoplak it would be great if we could get a small release with this change for our mapping file users.
> OPUSReader: OpusFC 1.1.0 support (multiregion and time-resolved 3D files)

- orangecontrib/infrared/preprocess.py
- orangecontrib/infrared/tests/test_preprocess.py
- orangecontrib/infrared/widgets/owpreproc.py
Looking for some feedback, not quite ready to merge.
Current vector normalization routine does not return the correct value.
Replaced custom implementation with `sklearn.preprocessing.normalize`, since it
(a) handles sparse data, (b) is faster and (c) minimizes unnecessary data copies.
In addition, "OPUS-style" vector normalization includes mean-centering the spectra
_before_ vector normalization, which is not what most users will expect, so I broke that out. Mean-centering is also useful for some data treatment workflows.
1. Naming of the different normalization routines
2. Refactoring the normalization routines into separate functions. Specifically,
is there an example best-practice I could follow, there are so many different
approaches in our/Orange codebase. I was thinking of …
> [RFC] Fix vector normalize

- orangecontrib/infrared/tests/test_owcurves.py
- orangecontrib/infrared/widgets/owcurves.py
self.curveplot.sample_indices isn't populated until update_view() is called. 
Also I don't think the other warning works either, if I feed `titanic.dat` to curves it doesn't trigger.
> OWCurves: showing_sample should be called after update_view()

- orangecontrib/infrared/data.py
Small mistake that prevented Start Time from being properly assigned as a TimeVariable.
> OpusReader: Fix Start Time meta variable loading

- orangecontrib/infrared/tests/test_owcurves.py
- orangecontrib/infrared/widgets/owcurves.py
Orange was changed so that schema_only settings are not reset
when Orange closes context.
> Spectra: adapt selected_indices for Orange master

- orangecontrib/infrared/data.py
- orangecontrib/infrared/tests/test_owfiles.py
- orangecontrib/infrared/widgets/owfiles.py
The files widget can now load many small files in spa, Envi, hdf5_hermes, and Omnic map format faster, because it does not construct a table for each file.
With Orange master I can now open 10000 1-spectra spa files in 10 seconds.
> Files: faster multiple file loading for some formats

- orangecontrib/infrared/widgets/owspectra.py
This was a fun one to track down. 
When you load data on a owintegrate widget, `self.curveplot.select_at_least_1` is set to `True`. This causes the `make_selection` function to be called in `owcurves.set_data` _before_ `self.data_x` is defined. The function `make_selection` tries to add a curve to the plot with x = None or [[0]] resulting in "Exception: Plot data must be 1D ndarray." from pyqtgraph (see traceback below).
For reasons unclear to me, this bug is not triggered when you run owintegrate by itself (as __main__), so I haven't included a test as I feel that I don't fully understand the error.
Traceback:
```
Traceback (most recent call last):
File "C:\Users\reads\AppData\Local\Continuum\Miniconda3-x86_64\envs\orange3\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line …
```
> owspectra: call make_selection in set_data after setting self.data_x (when self.select_at_least_1 is True)

- orangecontrib/spectroscopy/agilent.py
- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_readers.py
This accounts for the pixel binning used in the test data sets and fixes an error in the np.linspace XY coordinate generation which resulted in incorrect pixel sizes.
The related tests have been fixed and I added comments to explain where the numbers come from this time.
> agilent: Fix XY image coordinates and tests

- orangecontrib/spectroscopy/preprocess.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
Normalize preprocessor now output nans if attribute is invalid. This fixes preprocessor crashes if data is changed.
Since changes in Orange (PR "DomainModel: Prevent modification except through set_domain") NormalizeEditor was crashing, therefore I refectored NormalizeEditor internals to use DomainModel. 
Also fixed saved attribute loading.
> Fix Normalization in Preprocess Spectra

- .travis/install_pyqt.sh
The newest, 5.10, currently segfaults.
> Force PyQt5==5.9.2 on travis

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/preprocess/emsc.py
- orangecontrib/spectroscopy/tests/test_emsc.py
- orangecontrib/spectroscopy/widgets/owintegrate.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
I added simple EMSC to the "Preprocess Spectra" widget.
To do EMSC, we need a reference spectrum. Therefore I needed to add "Reference" input to the "Preprocess Spectra".
Are there any other preprocessors that would need something similar? I remember @clsandt once suggesting subtraction that would need something similar. Also, @stuart-cls made some preprocessors that use reference (Transmittance and Absorbance, but these were not passed from the widget).
If we add the "Reference" input (the alternative is to make a new widget that would be essentially the same but with different inputs), which name for the input would make sense? @borondics ?
> Preprocess widget: add EMSC

- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owspectra.py
This should be fixed in Orange, because many widgets have the same problems.
Domain in Orange transformations waste memory, because they copy X even though the same X could be used.
Now I have only temporarily fixed this for the viewers, but at least Integrate and Reshape suffer from the same problems.
A reference bug: #119
> Temporary workaround for needles data copy in annotated data

- orangecontrib/spectroscopy/tests/test_owmultifile.py
- orangecontrib/spectroscopy/widgets/owmultifile.py
This will allow users to select a custom reader where there are multiple
file readers with the same extensions.
>  Multifile: can select a specific reader for a group of files

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/widgets/owhyper.py
Resolves Sentry ORANGE-SPECTROSCOPY-Y:
ValueError:  min() arg is an empty sequence
Module "Orange.canvas.scheme.widgetsscheme", line 832, in process_signals_for_widget
handler(*args)
Module "orangecontrib.spectroscopy.widgets.owhyper", line 854, in set_data
self.imageplot.update_view()
Module "orangecontrib.spectroscopy.widgets.owhyper", line 543, in update_view
l1 = min(gx) - 1
> owhyper: fix integrals when given only metas

- orangecontrib/spectroscopy/tests/test_readers.py
The server serving the data went out of service.
> Skip nea test (file not served currently)

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/tests/test_owspectra.py
Fixes problems after Orange commit c13d5a6b88312fc5d3e91f79a344c3bcfdba0c58:
OWScatterOWScatterPlotGraph: Match group colors with marker colors
> Fix tests to work with changed order of group colors

- .travis.yml
Before, because the version was set to 3.7.0, and the oldest supported version was 3.11.0, Travis would uninstall 3.7.0 and install the current release for the tests, so the oldest version was never tested.
> Fix Travis to actually try the oldest supported Orange

- .gitignore
- .travis/check_pylint_diff
gitignore: ignore .pyline_cache generated by check_pylint_diff 
check_pylint_diff: handle system pylint installed as "pylint3"
affects at least Debian
> Pylint fixes

- orangecontrib/spectroscopy/tests/example_connect_settings.py
- orangecontrib/spectroscopy/widgets/gui.py
Someone programming a preprocessor requested a way to have movable lines that are relative to some value. Here is a short utility to do it with an example.
> A utility that can relate two settings: gui.connect_settings

- orangecontrib/spectroscopy/widgets/owpreprocess.py
Peak direction makes no difference and also not implemented, so we should disable the listbox.
> Disable peak direction selection list box for linear baseline

- orangecontrib/spectroscopy/widgets/__init__.py
- setup.py
1. Modified protocol because web view fallback fails due to problems with redirects.
2. Tested htmlhelp that can be installed locally when installing the package.
> Documentation that can appear in canvas

- .travis/install_orange.sh
Manually install CommonMark 0.7.5, because automatically installed CommonMark does not work for pre-3.16 Orange.
> Travis: temporary CommonMark fix

- orangecontrib/spectroscopy/widgets/owspectra.py
Removed use of `Orange.widgets.visualize.owscatterplotgraph.legend_anchor_pos` that was removed in  biolab/orange3#3260.
> Fixes for refactored owscatterplotgraph

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/preprocess/transform.py
- orangecontrib/spectroscopy/preprocess/utils.py
- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
Here is my attempt to put #76 #149 #128 to bed. I used Feri's GUI from #128 as a starting point.
Outstanding:
Non-goals:
- Handle references which are a subset of the data (like a reference FPA tile)
> [ENH] Unify spectral transforms preprocessor editor

- MANIFEST.in
Need to mention datasets manually in MANIFEST.in if I build the package on my Macbook with setuptools 38.4.0. 
I do not know why we need it there though. If I now rebuild old versions (0.3.6) that are fine on PyPi, the resulting package is missing the datasets.
> Add datasets/ to MANIFEST.in

- orangecontrib/spectroscopy/tests/test_conversion.py
Tests failed on Orange master due to biolab/orange3#3323
> Fix tests to work with DomainTransformationError

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_readers.py
It was inconsistent to automatically interpolate only two formats
Also, concatenating such files was impossible,
which led to problems if multiple of these files were read.
> Remove automatic interpolation with some readers

- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owintegrate.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
- orangecontrib/spectroscopy/widgets/owspectra.py
In the previews, highlight both the original and the processed sprectrum together.
I was showing effects of preprocessing to students but it was hard to see which spectra belonged together.
> owpreprocess: highlight pairs of spectra 

- orangecontrib/spectroscopy/widgets/owintegrate.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
For previews, preprocessors are executed within their corresponding Editor class. This allows the preprocessors to handle their own exceptions (show warnings in the interface).
Requested by @oroue for XAS and long time ago by @stuart-cls (#30).
There are no nice ways to report errors when processing final data yet.
> owpreprocess: execute preprocessors within the editor

- orangecontrib/spectroscopy/irfft.py
- orangecontrib/spectroscopy/tests/test_irfft.py
- orangecontrib/spectroscopy/widgets/owfft.py
Status: Review please :)
I am working on an overhaul of the FFT widget / `irfft` module. The main goal of this work is to support using stored phase / stored zpd values. A side benefit is cleaning up the `irfft` module.
- ~Provide user feedback on zpd (i.e. if stored value is being used)~ #250
- ~Allow manual specification of zpd~ #251
- ~Sanity check before averaging forward/backward spectra after FFT~ #252
- ~Handle (and test) multi-spectra stored phase / zpd condition~ #253
- ~Test all the things~ #252
> FFT overhaul

- orangecontrib/spectroscopy/tests/test_owaverage.py
- orangecontrib/spectroscopy/widgets/owaverage.py
A couple of fixes to work around issues with numpy / Orange handling of object arrays (which the meta arrays are whenever a `StringVariable` is present).
Implemented handling of unknown group_var values and group_var values with no members.
Related #237, #238
> OWAverage: Fix average group handling of metas and unknowns

- orangecontrib/spectroscopy/tests/test_conversion.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
I do not know why the numbers slightly changed, but in between I updated numpy and scipy.
> Fix preprocessor tests on some platforms

- MANIFEST.in
- orangecontrib/spectroscopy/agilent.py
- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_readers.py
Now the reader can load files without the interferogram tiles (*.seq / *.drd) being present (Fixes #194)
@markotoplak , can you check that I implemented the meta-reader for *.dat files properly?
Also is there anyway to hide the meta-reader in the File widget list? It's kind of ugly and distracting.
> [FIX] AgilentReaders: use correct file extensions

- orangecontrib/spectroscopy/data.py
> SpectralReader: do not create intermediate tables

- orangecontrib/spectroscopy/widgets/owpreprocess.py
I think preprocessors should not fill from before when putting a new widget on canvas.
> owpreprocess: make saved preprocessors schema only

- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/utils.py
- orangecontrib/spectroscopy/widgets/owspectra.py
Averages temporarily allocated lots of memory, both for selection and for the nanmean/nanstd. That computation was split column-wise into smaller chunks.
> owspectra: use less memory for computing averages

- orangecontrib/spectroscopy/agilent.py
- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_owfft.py
- orangecontrib/spectroscopy/tests/test_readers.py
- orangecontrib/spectroscopy/widgets/owfft.py
If the dataset contains laser wavenumber (and optionally, interferogram sampling interval or UDR) metadata, use that instead of the hard-coded / custom dx.
Note this builds on #262 so should wait on that being resolved first.
> [ENH] OWFFT: use laser wavenumber and sampling interval metadata if present

- .travis.yml
The error:
ImportError: dlopen: cannot load any more object with static TLS
> Use ubuntu xenial for travis to avoid static TLS limits

- doc/widgets/preprocess-spectra.rst
- orangecontrib/spectroscopy/tests/test_owintegrate.py
- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
@achimkohler reported the following error with the next schema
The upper result looks like: EMSC pre-process spectra are flipped: I think raw spectra are averaged and used as reference, while the averaged derivated spectra should be used
The lower stream results in (output from Preprocess Spectra (2)): Her you can see that the EMSC preprocessed spectra are not flipped compared to the derivated spectra:
I think that preprocessing reference data with the same preprocessors as we process input data makes sense. If someone wants old behavior, they can still have it by using 2 preprocess widget instead of one.
The older workflows should still work the old way but give a warning.
> [FIX] Preprocessors in the Preprocess Spectra widget also preprocess the reference

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_owmultifile.py
- orangecontrib/spectroscopy/tests/test_readers.py
- setup.py
Remove a binary-only module from the requirements. Opening an Opus file produces an error that instructs the user which library to install.
Fixes gh-190. Merge when Quasar packages are available.
> Remove opusFC from requirements

- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
Preprocessors were only saved before if they were applied.
storeSpecificSettings was not called otherwise.
> [FIX] Fix preprocessor saving

- orangecontrib/spectroscopy/tests/test_readers.py
data.py is an important part of the code but has very low coverage for tests...
> Added test for IOError the Matlab reader to increase coverage

- orangecontrib/spectroscopy/widgets/owpreprocess.py
Preprocessors that display warnings need to inherit BaseEditorOrange. Now, BaseEditorOrange creates a layout with a (hidden) message bar, therefore preprocessor editors need to add controls to .controlArea, which lies above the message bar.
This PR also shows how it issue warnings in the CutEditor. Something like this could be used for #30.
> [ENH] Preprocessor warnings

- orangecontrib/spectroscopy/preprocess/utils.py
- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
Preprocess spectra can now show exceptions that occurred during preprocessing as errors.
Exceptions that will be shown as errors in the widget need to be subclasses of PreprocessException.
> [ENH] Show preprocessor exceptions as errors in Preprocess Spectra

- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owspectra.py
CurvePlots now only use thick pen for selections up to 10 curves because drawing paths with width != 1 is very slow in Qt. Because CurvePlot now never draws more that 10 thick curves, we increased the previous limit to 1000.
Also, some other optimizations were needed.
> [ENH] Increase shown spectra limit from 100 to 1000 

- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owspectra.py
I introduced this bug with the thick/thin selected curve optimization.
> CurvePlot: fix select_at_least_1

- orangecontrib/spectroscopy/widgets/owpreprocess.py
I think this makes sense because now users can see which corresponding pairs of spectra.
> [ENH] OWPreprocess: show up to 100 preview spectra

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
Includes test.
I didn't touch the "FIXME notify user" on this `Except` block because updating/improving the baseline subtraction editor is a rabbit-hole I don't have time for right now. Plus it's Friday afternoon :)
> [FIX] Fix rubberband (qhull) ValueError on all-NaN sample row

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/preprocess/transform.py
- orangecontrib/spectroscopy/preprocess/utils.py
- orangecontrib/spectroscopy/tests/test_conversion.py
- orangecontrib/spectroscopy/tests/test_editor_normalize.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
Part of #302 
Changed attribute name for Absorbance and Transmittance to "reference" to standardize naming (no longer needed in the PR but I left it in)
> Test and handle (-) infs in preprocessors

- orangecontrib/spectroscopy/irfft.py
I think simply subtracting the ifg.mean() should be OK as we can assume that the IFG is good quality, which will mean that the points at the DC level will be overwhelmingly more than the centerburst ones, which should be symmetric around the DC anyway.
> [FIX] Subtract DC value from IFG

- orangecontrib/spectroscopy/widgets/owpreprocess.py
Preprocess Spectra widget segfaulted if it was removed while preview info labels were still shown. A quick way to crash it was adding a widget (connected to the data) and removing it immediately.
> [FIX] owpreprocess: fix segfault on widget removal

- orangecontrib/spectroscopy/tests/test_owmultifile.py
- orangecontrib/spectroscopy/widgets/owmultifile.py
The sheet combo box was linked to an used context setting which caused the combo box to show wrong value.  Hopefully fixes #266
> [FIX] Multi file widget: fix showing wrong sheet

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/preprocess/utils.py
CommonDomainOrderUnknowns: do not pass NaN rows further
Fixes error with EMSC on my machine on all_nans test:
File "/Users/marko/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 2156, in lstsq
x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
ValueError: On entry to DGELSD parameter number 6 had an illegal value
Fixes error with EXAFS on built packages on all_nans test:
ValueError: array must not contain infs or NaNs
> [FIX] Fix handling rows with all-NaN values

- orangecontrib/spectroscopy/tests/test_owbin.py
- orangecontrib/spectroscopy/utils/binning.py
- orangecontrib/spectroscopy/utils/skimage/README.txt
- orangecontrib/spectroscopy/utils/skimage/shape.py
- orangecontrib/spectroscopy/widgets/owbin.py
- pylintrc
Simple block-view binning widget. This first version hard-codes assumptions that the hyperspectral data of interest is a hyperspectral cube from imaging data and that binning blocks are square.
In future should be n-dim or at least support 1-3 binning dimensions.
Uses code in #331
> [WIP][ENH] Block-view Binning Widget for hyperspectral images

- orangecontrib/spectroscopy/tests/test_owbin.py
- orangecontrib/spectroscopy/utils/__init__.py
- orangecontrib/spectroscopy/utils/binning.py
- orangecontrib/spectroscopy/widgets/owbin.py
- orangecontrib/spectroscopy/widgets/owstackalign.py
This PR 
- moves the NanInsideHypercube exception back out of the get_hypercube utility function
- changes the behaviour of the OWBin widget to produce nanmean binned data and warn the user instead of erroring
> [ENH] Hypercube: separate nan handling

- orangecontrib/spectroscopy/tests/test_owbin.py
- orangecontrib/spectroscopy/tests/test_utils.py
- orangecontrib/spectroscopy/tests/test_widgets_utils.py
- orangecontrib/spectroscopy/utils/__init__.py
- orangecontrib/spectroscopy/utils/binning.py
- orangecontrib/spectroscopy/widgets/owbin.py
This adds support to OWBin for n-dimensional binning and non-square block shapes.
* `MAX_DIMENSIONS` is arbitrarily set to 5 to slightly simplify the GUI
* `utils.get_hypercube` has been generalized, but I kept `get_hypercube()` for simplicity / backwards compat
* I did **not** do a settings migration as the first version of OWBin has not actually been released
* ~I added a special case for 2-dimensional datasets: the code reverses the attr order (assuming the user sets Axis 0 to "x" and Axis 1 to "y") to maintain the row-major image table order. This is tested in `test_hypercube_roundtrip`~
> [ENH] OWBin: n-dimensional binning and non-square block shape

- pylintrc
Pylint currently crashes on my machine and also on travis. This makes the crash go away.
> Remove pylintrc ignore that was crashing pylint

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_readers.py
- simplified the code so that it uses the same functions as other readers
- fixed the data indexing to be consistent with Gwyddion and NeaSpec orientation
- added tests for checking pixel values
> [FIX] GSF file reader data indexing

- orangecontrib/spectroscopy/agilent.py
- orangecontrib/spectroscopy/data.py
- Data was being copied from full float32 array to full float64 at end of
file load, requiring over twice the memory space necessary
- Added parameter to python-agilent-file-format to directly fill mosaic
array as float64
> [FIX] agilent: avoid unnecessary memory copy during dtype float64 cast

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_readers.py
Avoid lxml dependency in NeaReaderGSF.
Also, the output is now a python list instead of a numpy array.
> NeaReaderGSF: avoid lxml dependency

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_readers.py
I realized that I made a mistake.
This change is necessary to view the X and Y axes in the hyperspectral data.
I took the opportunity to insert a key in the attributes, that key will be very important for the FFT - I will finish it soon.
> [FIX] NeaReaderGSF: Changed order of metas in NeaReaderGSF

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
Computing integrals does not block the widget anymore.
Also, while working on this, I noticed that the image was needlessly recomputed when a new spectra was chosen for integral preview.
> [ENH] Responsive Hyperspectra widget

- orangecontrib/spectroscopy/irfft.py
- orangecontrib/spectroscopy/tests/test_irfft.py
- orangecontrib/spectroscopy/tests/test_owfft.py
- orangecontrib/spectroscopy/tests/time_irfft.py
- orangecontrib/spectroscopy/widgets/owfft.py
Enhancements to the FFT processing as mentioned in https://github.com/Quasars/orange-spectroscopy/issues/360.
Currently showing speedups of 1-10x depending on datasize. Chunking into batches 100 as suggested by @markotoplak keeps the speed improvements but completely mitigates memory issues.
This code is only used for datasets with fixed, constant zpd values. The code I wrote to support variable zpd values from a peak search was too complex and fragile. Since this speedup is mostly useful for large imaging-array detector datasets, I think this is an acceptable tradeoff.
Not in scope: Fix the poor API boundary between irfft and owfft and add a preprocessor layer for use in scripts. That will be next.
> [ENH] FFT multirow processing

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_readers.py
`NeaReaderGSF` added attributes to _additional_table_, but `build_spec_table` didn't include them in the final table output.
Includes test :)
> [FIX] build_spec_table: respect additional_table.attributes

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_readers.py
Spectroscopy adds file formats, which are then also tested by Orange tests.
Fix some bugs:
- Remove a Writer that was not supported
- Make another writer not fail, because there is no error reporting mechanism in OWSave yet.
> Compatibility with Orange Save widget tests

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/widgets/preprocessors/normalize.py
At the request of users from Spain.
Standard Normal Variate is calculated by mean centering the spectra and subsequently dividing each with its standard deviation.
> Added SNV normalization

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
That makes the range=1 and also works for derivatives, when can be negative. This should be similar behaviour as in Unscrambler.
Thanks @clsandt.
> Normalize, MinMax: no shifting, only division by range

- doc/conf.py
- doc/widgets/preprocess-spectra.md
I try to types of more sophisticated typesetting:
- using HTML tags for sub- and superscripts
- using Latex annotations for equations. Markdown should be able to handle this but not sure how the documentation will look like... Maybe additional packages will be needed?
> Improved Preprocess Spectra Documentation

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/widgets/owhyper.py
Fixes #422
Before, the levels for the color palette were set according to the displayed image values. For selections of the data, some values can be missing. If missing values were on the edges of variable.values, the colors were wrong. Color palette levels for categoric variables are now manually set to span all possible values.
Also disable color legend when not applicable.
> [FIX] HyperSpectra: fix coloring by categoric variables with missing values

- orangecontrib/spectroscopy/widgets/owpreprocess.py
Based on https://stackoverflow.com/questions/53978542/how-to-use-collections-abc-from-both-python-3-8-and-python-2-7
> Fixes DeprecationWarning for importing from collections

- .travis.yml
- conda/meta.yaml
- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/tests/test_readers.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- setup.py
Hi!
Sorry, I didn't start discussion in issues, since we discussed it at meetings.
Here is the following changes:
- Save all visible (microscopic) images (bytes, title, position and pixel size) from opus file into `data.attributes: dict[List[dict]]`;
- Bytes unpacked into `np.ndarray` with pillow package just before displaying it in `imageplot` (to save memory);
- Visible image can be selected from combo box;
- User can change opacity of visible image;
- User can select composition mode (Normal, Overlay, Multiply, Difference);
I don't have a good lightweight file to put in tests for Opus. The one I have weights 150 MBs
Closes #118
> [ENH] HyperSpectra: display visible image

- README.pypi
- setup.py
I am opening this pull request to format the PyPI readme with the same format than other Orange3 addons use. This way all addons have the same format for description in the Orange add-on dialogue. 
You are welcome to suggest any modification to this PR.
> Readme for PyPI

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/widgets/owhyper.py
A bug caused by a fix in #462. Sorry.
This bug is present in the latests Spectroscopy release (0.5.5). Release 0.5.4 (and the latest Quasar) are fine. @borondics already reported this in the beginning of September.
> [FIX] Hyperspectra: do not crash with continous attributes

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_readers.py
In fact, comma-delimited is the default output for OPUS!
I added a test as well with some simple synthetic data.
> [FIX] AsciiColReader: .dpt files can also be comma-delimited

- orangecontrib/spectroscopy/agilent.py
- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/widgets/owhyper.py
Building on the great work in #443 , thanks again @pisarik 
Ref #118 
One thing I've noticed is that having the image stored in `attributes` dict as bytes makes the **Data Info** widget and `data.attributes` command slow / unusable. I think because they try to print/format megabytes of data. 
Not for this PR, but what about passing around a `BytesIO` object (or basically anything that could be an input to the `Image.open()` function in `update_visible_image()`)? 
For the latter the Agilent data could then wait to actually load the image data until requested, since the images are stored as separate files.
> [ENH] Agilent: Load visible images for mosaic data

- orangecontrib/spectroscopy/agilent.py
- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/tests/test_readers.py
- orangecontrib/spectroscopy/widgets/owhyper.py
(Builds on #483, look at last commit for changes just in this PR)
Fixes the problem discussed in #483 where **Data Info** and `print(data.attributes)` struggle with printing large amounts of image `bytes`. 
My solution is to change the object passed in the dict to be something directly consumable by `PIL.Image.open()`:
* `io.BytesIO` for OPUS
* `pathlib.Path` for agilent
A few notes:
1. I found the tests insensitive to changing the structure of the img dict to remove img_bytes. I guess because the tests use a lot of synthetic code paths to avoid large actual data files. 
2. I don't seem to have the file for `test_one_visible_image_read` in `test_readers.TestOpusReader` so unsure if I correctly adapted those.
3. Also in this file is the comment (L113)
`# decompress bytes only in widgets to …
> [FIX] Don't put bytes in Visible Images dict

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_readers.py
The library we use to open the files opens maps and line scans differently. The current code can now do both.
> [FIX] Renishaw map reading

- orangecontrib/spectroscopy/widgets/owhyper.py
Fixes #330
Earlier, I wasn't sure how to handle backwards compatibility but I think our minimum supported Orange version contains this `comboBox` now.
> [FIX] hyper: Use Feature combobox show all variables and searchable

- orangecontrib/spectroscopy/widgets/owspectra.py
Currently, the controlArea is only hidden, so the splitter is still visible. The proper way to dispose of the controlArea is to use teh `want_control_area` layout option.
Although, looking at the UX of the widget, wouldn't some controlArea options be relevant?
Similar to OWScatterPlot, different tools like Select, Zoom, Reset Zoom... As well as an autocommit control?
> owspectra: Remove (not hide) controlArea

- conda/meta.yaml
- setup.py
Christophe requested it because he would like fitting scripts to work easily in a new Quasar installation. Additional dependencies are negligible.
> Add lmfit to requirements

- orangecontrib/spectroscopy/widgets/gui.py
The text cursor was not shown in validated line edits.
> Fix cursor position display in numeric line edits

- orangecontrib/spectroscopy/widgets/owpreprocess.py
This fix is needed because the scroll area from orange-widget-base 4.12.0 (and possibly 4.11.0) reacts to size changes differently.
The problem looked like this (hiding and showing the control area would fix it though).
> owpreprocess: fix scroll area size propagation into controlArea

- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/tests/test_readers.py
Use smaller data sets for preprocessor widget tests
> Fix owpreprocess test timeouts

- orangecontrib/spectroscopy/utils/__init__.py
- orangecontrib/spectroscopy/widgets/owstackalign.py
A very low hanging fruit after @markotoplak told me about it but I am willing to do the easy stuff ;)
If this makes sense, we could replace those functions that have been implemented in faster libraries.
In this case I got a 10x speedup for a 1E6 size vector with 2 NaNs. Admittedly, the speedup was from 500 µs to 5 µs, but still, the 10x sounds good. I can't verify if this saves any memory though.
@markotoplak: should I move on with hunting down all the instances for this function? I can just add everything to this same pull request.
> Replacing slow numpy functions with faster bottleneck imlementations

- conda/meta.yaml
- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/preprocess/integrate.py
- orangecontrib/spectroscopy/preprocess/utils.py
- orangecontrib/spectroscopy/utils/binning.py
- orangecontrib/spectroscopy/widgets/line_geometry.py
- orangecontrib/spectroscopy/widgets/owaverage.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owsnr.py
- orangecontrib/spectroscopy/widgets/owspectra.py
- setup.py
This is faster and more memory-efficient.
For example, `np.nanmean` makes some auxiliary arrays and thus needs much more memory (at least 2x).
@borondics, I try to replace most of them, but I am sure I missed some. :) I focused on those working on big matrices, and I left some working on vectors as they were.
When I tried `numpy` vs bottleneck on 1GB array with `nanmean` I got significant differences. I think these won't turn into significant speedups except where `nanmean` used too much memory.
> Use bottleneck for np.array operations with nans

- orangecontrib/spectroscopy/widgets/owpeakfit.py
`Table.from_numpy` is evil because:
1) We easily forget to copy stuff. Before, .ids were copied, which is    great, but .attributes could also be important in some cases.
2) Addressing Table explicitly can make problems with subclasses of Table. Currently in Orange that happens with the text add-on, which uses Corpus. We also intend to implement out-of-memory tables, so let's start being more careful. :)
> peakfit: avoid Table.from_numpy

- orangecontrib/spectroscopy/tests/test_owpeakfit.py
- orangecontrib/spectroscopy/widgets/owpeakfit.py
Fixes #556 
Tests will fail until #557 is fixed as well.
> [FIX] OWPeakFit: Peak areas must account for x sample points

- orangecontrib/spectroscopy/tests/test_owpeakfit.py
- orangecontrib/spectroscopy/widgets/owpeakfit.py
The scope of this problem was actually very small: only peak area calculations were wrong.
Fixes #557 
Depends on #558
Otherwise:
* `lmfit` is insensitive to x ordering
* I ordered the x array for preview plotting evaluation, otherwise you get some exciting preview plots
* I didn't touch the output generation as the behaviour of most widgets is to leave the ordering alone and just handle it gracefully (as we now do)
> [FIX] OWPeakfit handle unordered x for area calculations

- orangecontrib/spectroscopy/tests/test_owmultifile.py
- orangecontrib/spectroscopy/widgets/owmultifile.py
The code had bugs after Orange transitioned from `Variable.make` to a different kind of handling values for `DiscreteVariables`; see the tests in the first commit.
Thanks to @VesnaT for finding the bug and working out the solution for non-spectral files.
> [FIX] Multifile widget: proper handling of nominal features with non-overlapping values

- orangecontrib/spectroscopy/widgets/owmultifile.py
0.6.0 packages (git repo was fine) unintentionally included a file owmultifile_vesna, which was a multifile widget with differently written internals. Because I deleted that file later, here is a migration (if users used that one).
> [FIX] A migration for a wrongly released owmultifile_vesna

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owspectralseries.py
Closes #487 
Added an option within the HyperSpectra widget to display an RGB image of 3 different, selected features. It contains GUI level controls which can be changed for each individual colour, however, there is no slider thresholding.
Tests and Documentation not yet done
@stuart-cls @markotoplak
> [ENH] RGB Visualization added to HyperSpectra Widget

- conda/meta.yaml
- orangecontrib/spectroscopy/widgets/owintegrate.py
- orangecontrib/spectroscopy/widgets/peak_editors.py
- orangecontrib/spectroscopy/widgets/preprocessors/integrate.py
- orangecontrib/spectroscopy/widgets/preprocessors/normalize.py
- orangecontrib/spectroscopy/widgets/preprocessors/utils.py
- setup.py
- tox.ini
I always disliked decimal limitations for input wavenumbers. I reviewed biolab/orange3#5647 today which used just what we need here.
Also, now spin boxes now do not call valueChanged after each edit which means that strange issues while typing are gone! So, fixes #564.
TODO:
> [FIX] Non-limited and typing-friendly spin-boxes

- orangecontrib/spectroscopy/widgets/owpeakfit.py
Built on #588 
Testing the changes above reminded me about one of the improvements stemming from #578 which is to provide good feedback to the user that the preview calculation is running (and therefore has been updated).
All this does is clear the results markings before starting the calculation.
> [FIX] Peakfit: clear preview markings before calculation

- orangecontrib/spectroscopy/tests/test_owpeakfit.py
- orangecontrib/spectroscopy/widgets/owpeakfit.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
- orangecontrib/spectroscopy/widgets/peak_editors.py
Prototyping what was discussed in #587.
This moves the complexity from `editor.param_hints` and `editor.setValues` into `ModelEditor._translate`. The `_translate` is not finished, but I think you'll get the idea. Yust wanted to show you something today...
@stuart-cls, what do you think? How does it perform for you?
To finish this we'd need at least:
> [FIX] Peakfit: refactor for stability and responsiveness

- orangecontrib/spectroscopy/tests/test_owpeakfit.py
- orangecontrib/spectroscopy/widgets/owpeakfit.py
- orangecontrib/spectroscopy/widgets/peak_editors.py
- orangecontrib/spectroscopy/widgets/peakfit_compute.py
- setup.py
`lmfit` uses `scipy.optimize`'s functions to perform the actual fitting. The problem there is that the optimizing functions block other threads from executing (time between threads is not shared). Therefore the interface blocks while fitting a single row, which, in some cases, can take long.
This PR aims to use multiprocessing in the processing threads.
On my Linux machine I get completely non-problematic previews. @stuart-cls, could you test this on Windows? Is it responsive? Asking because there might be a substantial process-spin-up difference between platforms.
> [ENH] Peak Fit: finally responsive (with multiprocessing)

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/tests/test_owpeakfit.py
getx() used to return `float32` arrays in some cases, which could not be serialized by python's json module within the lmfit library. Now it always returns `float64` arrays.
Had lmfit's `Model` had pickle, the world would have been a nicer place.
> peakfit: fix working with overridden wavenumbers

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/tests/test_owspectralseries.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owspectra.py
- orangecontrib/spectroscopy/widgets/owspectralseries.py
- orangecontrib/spectroscopy/widgets/utils.py
- setup.py
- tox.ini
Orange widgets, like Scatterplot, add a "Group" feature also to their "Selected data" output. Spectroscopy widgets only outputted selected groups in their Data output.
Spectroscopy visualizations were modified to behave as Orange visualizations. Because a new feature is added, this should be backward compatible.
Implements #168
~~**TODO** Think if this really is backward compatible. Some basic contexts, like the ones in Scatterplot, should work. How about Select Columns or perhaps some weird PerfectDomain contexts? If it is not perfectly backward compatible, add compatibility mode to the widgets.~~
I added the compatibility mode because there are cases where the new column makes trouble. The most obvious ones are when there are other widgets in the pipeline that also add "Groups", such as …
> [ENH] Visualizations: selection outputs groups

- orangecontrib/spectroscopy/widgets/owbin.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owspectra.py
- orangecontrib/spectroscopy/widgets/owspectralseries.py
- orangecontrib/spectroscopy/widgets/owstackalign.py
This PR removed checks for unchanged domains in the input; before, selected features were not updated if domains were the same. This could lead to problems with discrete variables, which now for some time have relaxed equality checking.
This is done with hopes of fixing exceptions when variables from settings and those available do not match. I saw bugs like this and have seen error reports on Sentry, but I do not know how to reproduce the bug. I do not know whether this change will fix the bugs I saw, but it seems to remove one possibility for errors.
An exception that I see on Sentry ([ORANGE3-2RF](https://sentry.io/organizations/biolab/issues/2755974424/?project=124497)) looks like this:
```
"  File \"/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python …
```
> [FIX] Always set correct feature comboboxes

- doc/widgets/atmcorr.md
- doc/widgets/preprocess-spectra.md
- orangecontrib/spectroscopy/preprocess/atm_corr.py
- orangecontrib/spectroscopy/tests/test_atm_corr.py
- orangecontrib/spectroscopy/tests/test_editor_als.py
- orangecontrib/spectroscopy/tests/test_editor_atm_corr.py
- orangecontrib/spectroscopy/tests/test_editor_baseline.py
- orangecontrib/spectroscopy/tests/test_editor_emsc.py
- orangecontrib/spectroscopy/tests/test_editor_gaussian.py
- orangecontrib/spectroscopy/tests/test_editor_me_emsc.py
- orangecontrib/spectroscopy/tests/test_editor_spikeremoval.py
- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
- orangecontrib/spectroscopy/widgets/preprocessors/atm_corr.py
Atmospheric gas correction, subtracting as much of a reference spectrum as needed to minimize the sum of squares of differences of consecutive points. Implemented as a preprocessor with options for the wavenumber ranges (which should be non-overlapping), replacing a region with a smooth curve, denoising the corrected region, and whether multiple reference spectra should be averaged first or later (with spectrum-specific weighting).
> [ENH] Atmospheric gas correction

- orangecontrib/spectroscopy/data.py
- orangecontrib/spectroscopy/io/ascii.py
- orangecontrib/spectroscopy/util.py
We were sloppy in #575. In the owfile settings, explicitly selected readers are stored with the full module and class names. Moving but not adding imports for compatibility showed the missing reader error. I remembered this bug while studying how owfile works.
I also needed to move `getx` somewhere out of `orangecontrib.spectroscopy.data` because of circular imports. `orangecontrib.spectroscopy.data.util` did not work because that still imported the parent module. I am open to better names than `orangecontrib.spectroscopy.util`.
> [FIX] Fix loading pre-0.6.1 workflows with explicit reader settings

- orangecontrib/spectroscopy/widgets/owspectra.py
The crosshair label was always jumping because the number digits are not the same width. Now I changed the font to a fixed-width font so this problem goes away. Also added an opaque BG to the label and moved it onto the top of the GUI elements stack so that the crosshair and other elements don't make the reading hard when overlapping.
> Fixed-width label font for crosshair label

- orangecontrib/spectroscopy/widgets/gui.py
This way the label can be read easier if it overlaps with something.
> Adjusted the fill color for the peak label

- orangecontrib/spectroscopy/utils/agilent.py
`agilent` module had a (case) typo in the hard-coded filenames for visible image loading. Doesn't show up on Windows as it is case-insensitive.
I added some files for testing in https://github.com/stuart-cls/python-agilent-file-formats/commit/07f278a33da008fc4e21872b9d4e98a35e02acc7 but I wasn't sure if we wanted even those small-ish `.bmp` files here. If yes, I can add a similar test to this PR
> [FIX] Agilent visible image loading on case-sensitive systems

- .github/workflows/lint_workflow.yml
- .github/workflows/test.yml
- conda/meta.yaml
- setup.py
- tox.ini
Preparation for #615, which requires `shared_memory`.
In Biolab we discussed dropping support for 3.7 and the main Orange repo will soon follow suite.
Also update tests for newer runners following what Orange did.
> Require Python 3.8 and Orange 3.31

- orangecontrib/spectroscopy/tests/test_conversion.py
- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/widgets/preprocessors/atm_corr.py
biolab/orange-widget-base/pull/204 pointed out an error that we did not catch before. @stuart-cls, remember when we were wondering why some exceptions in peak fitting did not fail the tests? Well, now they would.
I am surprised there was just a single error like this.
> Fix a crash in athmospheric correction (in an extremely degenerate case)

- orangecontrib/spectroscopy/utils/pymca5/OmnicMap.py
@clsandt found a map where:
- deltaX = 49.97058868408203
- x0 = -815.0
- x1 = 884.0
The number of jumps (intervals) in X is ((x1 - x0) / deltaX) which is 33.9999996946446, which means that the number of measurements nX is 33.9999996946446 + 1.
The old code wrongly rounded this down. The new code rounds before converting to int so it is more robust to numeric inaccuracies.
The reading code comes from PyMCA so I also opened a pull request there: vasole/pymca#906
> Fix OmnicMap's reader getPositionFromIndexAndInfo

- conda/meta.yaml
- orangecontrib/spectroscopy/tests/test_readers.py
- setup.py
Fixes #628.
Reference issue: #144
> Avoid spectral 0.23 due to problems on Windows

- .github/workflows/test.yml
The "oldest" tests in #632 aren't passing, but there's no way currently to check if the master branch CI tests pass. In travis we could trigger a run (and run on a schedule) so that's what this change does.
My cron-fu is not strong but I think it's set to run on the 1st of each month.
> github actions: run tests monthly and on-demand

- orangecontrib/spectroscopy/io/agilent.py
- orangecontrib/spectroscopy/tests/test_tile_reader.py
I found that the `agilentMosaicTileReader` had an error in the way it calculated the y-axis positions. Although the agilent data xy positions are arbitrary from (0,0), it means the TileReader and the normal reader generate _different_ positions.
I'm asking for input because this has implications for backwards compatibility. In the case where someone uses the **OWTileFile** widget and then selects regions in **OWHyper**, the selection will be incorrect when that workflow is loaded with this code.
Thoughts?
Edit: This now fixes both the coordinates and the table row ordering so that the two readers result in identical output.
> [FIX] Agilent Tile Reader: Generate correct y-axis positions

- orangecontrib/spectroscopy/datasets/peach_juice.dpt
- orangecontrib/spectroscopy/io/ascii.py
Such comments are contained in the files exported by the Kazan viewer.
This change does not break previous kind of comments (starting with "#")
> [FIX] Ascii column reader: allow comments starting with ";"

- .github/workflows/test.yml
- tox.ini
As described in #378, OrangeDeprecationWarnings that came into Qt's event loop caused segfaults (Qt does not like exceptions).
This PR disables crashes on OrangeDeprecationWarnings for unreleased Orange versions.
> On -latest tests, do not crash in case of OrangeDeprecationWarnings

- orangecontrib/spectroscopy/__init__.py
- orangecontrib/spectroscopy/widgets/owaverage.py
- orangecontrib/spectroscopy/widgets/owfft.py
- orangecontrib/spectroscopy/widgets/owsnr.py
The replacement, `get_column`, also takes care of the conversion into the correct data type.
> Replace deprecated get_column_view

- orangecontrib/spectroscopy/tests/test_tile_reader.py
- orangecontrib/spectroscopy/tutorials/tile-loader.ows
- orangecontrib/spectroscopy/widgets/owtilefile.py
Implements #634, depends on #637 for OWIntegrate testing.
A few notes/items for discussion:
- **OWIntegrate** "Output as metas" checkbox is not reflected in the preprocessor box
- I found looking at all the PreprocessorList and PreprocessorListMoveMetas was distracting, but the preprocessors from OWIntegrate all have meta=True set, and then move metas around later. It works fine, but isn't shown.
- Coming back to #439, we had talked about just getting rid of this checkbox and have the Preprocessor output simply always do `move_metas=True` + `metas=True` (which is the equivalent of multi-method `metas=False` from Preprocess Spectra)
- I found that the WidgetPreview doesn't support multi-input: a bug? I worked around it with some awkward syntax.
- I didn't update the code-copy from OWFile, …
> [ENH] OWTileFile: Multi-input for Preprocessor chaining

- orangecontrib/spectroscopy/__init__.py
- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owintegrate.py
Thanks to @clsandt for pointing out the bug. At first I just wanted to disable this functionality, but then I decided to actually support it.
> [FIX] HyperSpectra now works with integrals with separate baselines

- orangecontrib/spectroscopy/widgets/owtilefile.py
Following #638 
[Edit: Left None bug for another day, see #648]
I found a bug where the code that runs the preprocessor() wasn't checking for `PreprocessorList`s with None in them (or empty lists), so `PreprocessorList` tries to call None(). But I kept thinking of more weird edge cases from the multiple inputs, so I decided instead to just not add None in the first place (which is cleaner, I think).
But now when you have a `None` connected (empty Preprocess Spectra), and then change it to a preprocessor (Add an editor to the Preprocess Spectra), it crashes because the index state from the `MultiInput` doesn't match the PreprocessorList length.
@markotoplak  Before I go any further down this rabbit hole, any thoughts?
> [FIX] OWTileFile warn on preprocessor change

- orangecontrib/spectroscopy/io/opus.py
This makes a whole class of opusFC bugs less annoying to users.
Also today I learned that warnings are nicely propagated up to the File widget!
> [FIX] io.opus: Convert visible image loading Exceptions to warnings

- orangecontrib/spectroscopy/tests/test_owmultifile.py
- orangecontrib/spectroscopy/widgets/owmultifile.py
Fixes #659 
The problem appears because wavenumbers are compared as numbers at one point and as strings at another (using "%f", so rounded). 
If wavenumbers collide when converting to string, the required precision is computed and used instead. Some wavenumbers will there be more precise than other.
I tried to keep perfect backward compatibility - whatever could be read should be read exactly the same now.
> [FIX] Multifile: fix a bug when wavenumbers differ for less than 1e-6

- orangecontrib/spectroscopy/widgets/owinterpolate.py
I guess I don't use these boxes that often :)
I also noticed searching around for any other instances of this that OWAverage is still using the old commit style. I didn't touch it in this PR.
> [FIX] owinterpolated: Call commit.deferred in line edit callbacks

- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owspectra.py
Previously, the context menu of OWSpectra didn't display keyboard shortcuts on Mac (Ventura) and the window edges were very close to the elements. 
Now this is changed to the following:
Needs testing on Linux and Windows.
> [ENH] Improved the context menu display on Mac

- orangecontrib/spectroscopy/io/gsf.py
- orangecontrib/spectroscopy/io/util.py
The problem was actually a misbehaving reader that did not return the correct types.
The problem:
```
Traceback (most recent call last):
File "/home/marko/dev/orange-spectroscopy/orangecontrib/spectroscopy/widgets/owmultifile.py", line 415, in browse_files
self.load_files(filenames, reader)
File "/home/marko/dev/orange-spectroscopy/orangecontrib/spectroscopy/widgets/owmultifile.py", line 426, in load_files
self.load_data()
File "/home/marko/dev/orange-spectroscopy/orangecontrib/spectroscopy/widgets/owmultifile.py", line 487, in load_data
data = concatenate_data(data_list, fnok_list, self.label)
File "/home/marko/dev/orange-spectroscopy/orangecontrib/spectroscopy/widgets/owmultifile.py", line 98, in concatenate_data
xs = reduce(numpy_union_keep_order, xss, np.array([]))
File …
```
> [FIX] Fix opening GSF files in Multifile

- orangecontrib/spectroscopy/preprocess/utils.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
Renames are saved into the domain so that also new data can be transformed in the same way.
This was Feri's idea. He asked how to transform X and I figured it would be, for starter, nice to have a utility function that does that.
> A utility function that can easily replace wavenumbers (x)

- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owspectra.py
This prevents blocking canvas with Dask data sets.
This change is independent of dask and can be tested with normal data sets. This PR changes `CurvePlot`, the basic display components, thus all widgets using it need to be tested.
> [ENH] Spectra: individual display in its own thread

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/utils/__init__.py
- orangecontrib/spectroscopy/widgets/owhyper.py
Fixes #686
Handle (and also test) degenerate inputs.
#686 described errors that happened for the SNR widget because the widget is not meant to be used on normal data (without data point repetitions). HyperSpectra now does not crash but in the (before crashing) cases does not do anything useful either.
> HyperSpectra: handle degenerate (all nan) coordinates and data

- orangecontrib/spectroscopy/models/pls.py
- orangecontrib/spectroscopy/tests/test_owpls.py
- orangecontrib/spectroscopy/widgets/owpls.py
For me this makes PLS actually useful. I know improvements are possible, for starters supporting multiple targets, but this perhaps closes #283.
> [ENH] PLS: scores and loadings outputs

- orangecontrib/spectroscopy/models/pls.py
- orangecontrib/spectroscopy/tests/test_owpls.py
- orangecontrib/spectroscopy/widgets/owpls.py
But none of the other Orange widgets, such as Predictions or Test and Score, do.
> [ENH] PLS supports multiple targets

- conda/meta.yaml
- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/preprocess/als/__init__.py
- orangecontrib/spectroscopy/preprocess/emsc.py
- orangecontrib/spectroscopy/preprocess/integrate.py
- orangecontrib/spectroscopy/preprocess/me_emsc.py
- orangecontrib/spectroscopy/preprocess/transform.py
- orangecontrib/spectroscopy/preprocess/utils.py
- orangecontrib/spectroscopy/tests/test_integrate.py
- orangecontrib/spectroscopy/tests/test_interpolate.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/tests/test_preprocess_utils.py
- setup.py
- tox.ini
Two different Preprocess Spectra widgets with the same parameters for Savitzky-Golay produced transformations, that always gave equivalent results, but because nothing guaranteed that they were different they were regarded as incompatible. Implementing `__eq__` and `__hash__` on transformations educates Orange about equivalence. With Savitzky-Golay it now looks like this (both workflows would trigger a warning before the change):
This feature builds on biolab/orange3#5985 and company.
> [ENH] Implement equivalence of (some) spectral tranformations

- orangecontrib/spectroscopy/preprocess/emsc.py
- orangecontrib/spectroscopy/preprocess/me_emsc.py
- orangecontrib/spectroscopy/preprocess/npfunc.py
- orangecontrib/spectroscopy/preprocess/utils.py
- orangecontrib/spectroscopy/tests/test_emsc.py
- orangecontrib/spectroscopy/tests/test_me_emsc.py
- orangecontrib/spectroscopy/tests/test_preprocess_utils.py
> EMSC: __eq__ and __hash__

- orangecontrib/spectroscopy/preprocess/atm_corr.py
- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
Before, the exception was silently ignored, which prevented us from notifying users of incompatible workflows.
> Show an exception if preprocessors can not be loaded

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/tests/test_owspectra.py
- orangecontrib/spectroscopy/widgets/owbin.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- orangecontrib/spectroscopy/widgets/owsnr.py
- orangecontrib/spectroscopy/widgets/owspectra.py
- orangecontrib/spectroscopy/widgets/owspectralseries.py
- orangecontrib/spectroscopy/widgets/owstackalign.py
Some contexts match even though feature-selection combo boxes do not show the feature. Problematic settings are those where combo boxes are limited to specific parts of the table (attributes, class_vars, or metas).
This partial solution follows from https://github.com/biolab/orange3/issues/6721#issuecomment-1923826563. This does not solve the problem completely, but if problem appears, adding a new widget instance allows the user to continue.
Also, there is another minor issue: exclude_attributes won't allow users to reuse contexts where class vars were used in the fields (current implementation handles attributes and class vars in the same way), but saving and loading works properly (because of perfect matches).
> [FIX] Avoid some context crashes: exclude_attributes=True

- orangecontrib/spectroscopy/io/maxiv.py
- orangecontrib/spectroscopy/io/neaspec.py
- orangecontrib/spectroscopy/io/soleil.py
- orangecontrib/spectroscopy/utils/spc/spc.py
- setup.py
Aims to close #705
This could also introduce new problems for users with text files in other encodings. I'll pretend it will solve more issues that it causes.
> [FIX] Explicitely define utf8 encoding on open() for text files

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/preprocess/emsc.py
- orangecontrib/spectroscopy/preprocess/integrate.py
- orangecontrib/spectroscopy/preprocess/me_emsc.py
- orangecontrib/spectroscopy/preprocess/transform.py
- orangecontrib/spectroscopy/preprocess/utils.py
- orangecontrib/spectroscopy/tests/test_emsc.py
- orangecontrib/spectroscopy/tests/test_integrate.py
- orangecontrib/spectroscopy/tests/test_interpolate.py
- orangecontrib/spectroscopy/tests/test_me_emsc.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
It can be so slow that it appears Orange has crashed.
With @borondics we had a workshop in Berlin and preprocessing appeared to crash for most students. We thus downgraded to a previous version.
After debugging I saw that a series of preprocessors causes domain comparisons to be very long (for example, after normalization, each feature in turn references the whole original domain, and then equality checking just multiplies).
> [FIX] Disable __eq__ and __hash__ because it can be slow

- orangecontrib/spectroscopy/tests/test_owpeakfit.py
This test would have caught the issue in #720 more explicitly. It will fail until the bug is fixed upstream.
> [TEST] Add a test to check peakfit_compute.pool_initializer restore

- doc/conf.py
- setup.py
https://www.bleepingcomputer.com/news/security/polyfillio-javascript-supply-chain-attack-impacts-over-100k-sites/
> Remove https://polyfill.io/v3/polyfill.min.js?features=es6 (security issue)

- orangecontrib/spectroscopy/io/agilent.py
- orangecontrib/spectroscopy/io/opus.py
- orangecontrib/spectroscopy/io/util.py
- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/tests/test_readers.py
- orangecontrib/spectroscopy/widgets/owhyper.py
- setup.py
@clsandt reported running out of memory when performing PCA on Opus data with large visual images.
That was caused by the `.attributes` dictionary on a table that contained actual visual images, and that dict was deepcopied for each table transformation. Thus, memory got filled up quickly.
This PR now uses a subclass of `VisibleImage` that does not actually deepcopy the image data on copying and just reuses the same references.
This is my preferred alternative to #725, because then saving data in .tab or .pickle formats keeps the images working; images actually get saved into .metadata file (or directly into .pickle).
> [FIX] Less memory use with visible images (reimplemented deepcopy)

- orangecontrib/spectroscopy/widgets/owpreprocess.py
- orangecontrib/spectroscopy/widgets/preprocessors/atm_corr.py
- orangecontrib/spectroscopy/widgets/preprocessors/registry.py
- orangecontrib/spectroscopy/widgets/preprocessors/spikeremoval.py
- orangecontrib/spectroscopy/widgets/preprocessors/utils.py
Implements https://github.com/Quasars/orange-spectroscopy/issues/446 with simple submenus.
Each editor can belong to multiple categories.
Replacement for #728 so that the changeset is smaller and so that the code remains closer to what preprocess widget in Orange does.
> [ENH] Preprocess Spectra: supports categories of preprocessors

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
- orangecontrib/spectroscopy/widgets/preprocessors/misc.py
Add a scale factor to the CurveShift preprocessor in order to enable scaling the spectra amplitude, now results in a form:
res = scale * spectra + amount.  Also, rename it into LinearTransform for coherence.
> Extend shift spectra

- orangecontrib/spectroscopy/tests/test_als.py
- orangecontrib/spectroscopy/tests/test_atm_corr.py
- orangecontrib/spectroscopy/tests/test_conversion.py
- orangecontrib/spectroscopy/tests/test_cut.py
- orangecontrib/spectroscopy/tests/test_despike.py
- orangecontrib/spectroscopy/tests/test_emsc.py
- orangecontrib/spectroscopy/tests/test_integrate.py
- orangecontrib/spectroscopy/tests/test_interpolate.py
- orangecontrib/spectroscopy/tests/test_me_emsc.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/tests/test_tile_reader.py
- orangecontrib/spectroscopy/tests/test_xas.py
Testing common preprocessor functionality - also lovingly called torture tests - relied on putting preprocessors into a special list in `test_preprocess.py`. This prevented reusing tests in other repositories.
An example of a PR that could benefit them: Quasars/orange-snom/pull/4
This PR refactors preprocessor tests so that torture tests can now be mixed into the test class.
> [MNT] Refactor preprocess tests

- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- orangecontrib/spectroscopy/widgets/owpreprocess.py
- orangecontrib/spectroscopy/widgets/preprocessors/misc.py
Added a new denoising method with the help of SOLARIS colleagues.
The paper it is based on is [this](https://doi.org/10.1371/journal.pone.0205219).
> [ENH] Minimum Noise Fraction denoising preprocessor

- doc/widgets/peakfit.md
- orangecontrib/spectroscopy/widgets/owpeakfit.py
Fixes #743 
Can be overridden with new env var `QUASAR_N_PROCESSES=all`
Documented in the widget documentation. We can move it later if we use it more places.
I was going to add tests* but it seems `unittest` always gives you `cpu_count()==1` (so that part works at least) and mocking environment variables in `unittest` is annoying.
Edit: I did test the permutations on a large multicore machine
> [FIX] peakfit: limit multiprocessing to 2 processes during fitting to avoid crashes

- orangecontrib/spectroscopy/widgets/owhyper.py
Preprocess image from the SNOM addon can also modify the contents of axis variables. Therefore it is not the same variable, but matching by name is sufficient.
> ImagePlot: do not require exact attribute, just matching names

- orangecontrib/spectroscopy/io/agilent.py
- orangecontrib/spectroscopy/io/ascii.py
- orangecontrib/spectroscopy/io/opus.py
- orangecontrib/spectroscopy/io/ptir.py
- orangecontrib/spectroscopy/io/util.py
- orangecontrib/spectroscopy/utils/__init__.py
Working on #615 reminded me of a class of little bugs I've been meaning to address: standard "map_x" / "map_y" variables
First commit replaces all "map_x" / "map_y" strings with constants
~Second commit shows how this can be used to reliably plot XY data in Hyperspectra if both these vars are present (otherwise reverts to existing behaviour.~
~If this works, I'll also apply to the other mapping-aware widgets (Bin, Stack, Polar, etc)~
> Standard map vars

- orangecontrib/spectroscopy/tests/test_owmultifile.py
Fixes #746
The new open_dialog windows does not propose all readable files option if there is only one format. Because the particular tests patches file formats so that there is only one, now the opening of files in tests wanted a specific reader, which it then could not find, because it was defined within the test method. Moving it out solved the issue.
> Rewrite multifle test for compatibility with different Orange versions

- orangecontrib/spectroscopy/io/neaspec.py
A new gsf reader that we discussed. Only reading the selected file using `reader_gsf` from utils and adding datatype to the attributes.
> [ENH] Single NeaGSF reader with measurement.signaltype attribute

- orangecontrib/spectroscopy/io/neaspec.py
#739 broke the existing Nea gsf reader. At least some of the files I see lack `"Interferometer Center/Distance"` and therefore it crashes.
> Nea .gsf files not always include Interferometer Center/Distance

- orangecontrib/spectroscopy/io/neaspec.py
Changes on the multichannel interferogram reader (NeaReaderMultiChannel) so it can check for wavenumber scaling factor metadata and apply it as a corresponding scaling factor to Δx (used by the fft). 
I think @raul-freitas can explain better how this is factor comes from the device generating the data, but in short it is calculated comparing the experimental data to reference values (i.e. water vapor lines) during the data collection. 
We discussed how to implement this in https://github.com/Quasars/orange-spectroscopy/pull/717 and now @raul-freitas validated the necessity of using this factor in the Δx calculated from the positional reference (M) we are using for this type of file.
> NeaReaderMultiChannel - Apply wavenumber scaling to Δx

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/widgets/owhyper.py
This one also works for "short" spectra, like images with 1 column.
The problem is that if you open an image that has only one "spectral" column, you see nothing useful because the default integral is not working (=returns all the same values). I propose changing it.
I did not want to do any smart detection because then whatever would be detected would also be saved as a default setting. We could perhaps do detection if these settings were "schema only".
> HyperSpectra: change the default integration method

- orangecontrib/spectroscopy/tests/test_owhyper.py
- orangecontrib/spectroscopy/widgets/owhyper.py
Solves the following error reported by @borondics. When you have the hyperspectra widget and make a line selection, everything is OK. However, if you load a different file into the same workflow, there is an error:
> [FIX] HyperSpectra: fix changing data with active line trace

- orangecontrib/spectroscopy/widgets/owcos.py
The import sequence wasn't working when the widget was started for te…sting because the **pyqtgraph** import was first. Thanks @markotoplak for the help!
Also removed some unused imports.
> import fix

- orangecontrib/spectroscopy/widgets/owhyper.py
HyperSpectra has too many options in the menu, and some of them are as important as the ones in the control area. I suggest to unify this.
I have been thinking about this for a while, especially when doing workshops and students do not understand, why do their images look so funny, when they only had strangely set axes. MY final motivation was #765, which adds additional options. Having less often used options in control panel and more common ones (especially axes) in the menu seemed off to me. Therefore, I tried this and to me it seems fine. 
Asking for comments, especially @stuart-cls and @borondics.
In #765 I also made visual image pane smaller if disabled.
> [ENH] HyperSpectra: move image properties to control area

- orangecontrib/spectroscopy/io/__init__.py
- orangecontrib/spectroscopy/io/maxiv.py
- orangecontrib/spectroscopy/io/soleil.py
This PR contains a change for the HERMES reader to ensure that the file is closed after reading and a new HDF5 reader for the Max-IV SoftiMax beamline that has almost the same entries as the HERMES (counter instead of Counter). Instead of doing some string manipulation magic I added a new class. Eventually it would be nice to unify these readers though.
Also, I will change the order of `x_locs` and `y_locs` in the HERMES reader because the current code will crash with non-square maps.
To come: small SoftiMax test file and reader test.
> [ENH] SoftiMax HDF5 reader

- doc/widgets/polar.md
- orangecontrib/spectroscopy/widgets/owpolar.py
Limits process count to prevent crash on windows installs. Temporarily copied from #748, aiming for a permanent fix later.
> [FIX] Polar: limit process count to prevent crashes on Windows

- orangecontrib/spectroscopy/tests/test_xas.py
scipy 1.5.0 curve_fit optimizes differently on some platforms
Perhaps this can be improved if the curve_fit within the optimization used the actual jaccardian?
> Fix xas failing tests due to scipy upgrades

- conda/meta.yaml
- orangecontrib/spectroscopy/preprocess/__init__.py
- orangecontrib/spectroscopy/preprocess/emsc.py
- orangecontrib/spectroscopy/preprocess/integrate.py
- orangecontrib/spectroscopy/preprocess/me_emsc.py
- orangecontrib/spectroscopy/preprocess/transform.py
- orangecontrib/spectroscopy/preprocess/utils.py
- orangecontrib/spectroscopy/tests/test_emsc.py
- orangecontrib/spectroscopy/tests/test_integrate.py
- orangecontrib/spectroscopy/tests/test_interpolate.py
- orangecontrib/spectroscopy/tests/test_me_emsc.py
- orangecontrib/spectroscopy/tests/test_owpreprocess.py
- orangecontrib/spectroscopy/tests/test_preprocess.py
- setup.py
- tox.ini
Now that orange3/pull/6764 is released in Orange 3.38, we can revert #713.
So this brings #625 back.
> [ENH] Re-enable equivalence of spectral tranformations

- conda/meta.yaml
- orangecontrib/spectroscopy/tests/test_owpeakfit.py
- setup.py
- tox.ini
> [FIX] Peak fit: swap the sign of the residuals (as lmfit 1.3.3)

- orangecontrib/spectroscopy/io/neaspec.py
- orangecontrib/spectroscopy/tests/test_readers.py
Previously the NeaImageGSF reader crashed if the filename did not contain the proper data channel string pattern. With the fix, instead of crashing, it reads the file and considers it a Topography type measurement.
> [FIX] NeaImageGSF fix: works without channel in filename

- orangecontrib/spectroscopy/widgets/owfft.py
Hi Everyone!
The complex FFT using complex-valued interferograms is crucial for asymmetric interferometry data such as DFTS or nanoFTIR.
Currently, the OWFFT widget only calculates complex FFT for a specifically defined datatable organization. Namely, if the data is not read by `NeaReaderGSF` or `NeaReaderMultiChannel`, there is no option for the user to do a complex FFT using amplitude and phase input data tables separately.
I modified the widget to correct the lack of flexibility of the widget so users can apply the processing to any data.
Additionally, there is an option for asymmetric or symmetric apodization, in general. As far as I heard, @stuart-cls might wanted to have something like this.
Modifications:
- New checkbox option for complex FFT
- `stored_phase` input is used as the …
> [ENH] OWFFT: Configure Complex FFT manually

- orangecontrib/spectroscopy/tests/test_owoverlay.py
- orangecontrib/spectroscopy/widgets/icons/overlay.svg
- orangecontrib/spectroscopy/widgets/owoverlay.py
The user can choose a feature from the "Overlay Data" input, which is added to the attributes of the "Data" input table as a "visible image". This way, it is possible to add a visible image overlay even if the reader cannot read it from the original data file, or if it is stored separately. 
The widget creates an RGB overlay image from the displayed image. Thus, changing the display parameters directly affects the assigned visible overlay image.
One of the tests does not seem to run correctly, even though in a real application, the same thing works. Somehow, during `test_add_visible_image`, the image acquired from the imageplot is None, because `im = self.imageplot.img.qimage` in `set_vimage` of the OWOverlay. However, everything runs correctly when the widget is used. 
@markotoplak : …
> [ENH] Add Image Overlay: new widget

- orangecontrib/spectroscopy/widgets/owoverlay.py
Thanks for the overlay widget, it's great!
I spent way too long trying to figure out why it was broken for me. This small change forces the uninitiated user to think about whether the dataset they are connecting is the one to be added or added to.
> owoverlay: Don't set default input
